### PR TITLE
Log error if invalid Bitmap passed to `FlxG.addBitmap()`

### PR DESCRIPTION
**Pull request by IQAndreas**
Resolves the following issue:
- FlxG.as line 738,743 undefined property bitmapData (https://github.com/FlixelCommunity/flixel/issues/15, https://github.com/AdamAtomic/flixel/issues/217)

### CODE REVIEW

**Comment by jquave** [comment]
I get an error from this commit:
/org/flixel/FlxG.as(754): col: 38 Error: Access of possibly undefined property ImgDefault through a reference with static type Class.

**Comment by IQAndreas** [comment]
Ah, my bad. I see what happened. It's a quick fix, so I'll get it up this weekend. 

Normally I make sure to "test compile" the code before commiting it, but I guess I forgot this time. Thanks for the catch, @jquave!

**Comment by jquave** [comment]
I'm thinking we can just make ImgDefault public static, but not sure how that effects the existing use of ImgDefault. in FlxSprite.as.

**Comment by Dovyski** [comment]
I imagine the only reason why `ImgDefault` is not public is to avoid some sort of "class cluttering" for newcomers. I believe the change from private to public won't break anything and it's quite useful :)

**Pull request merged**
