### PR TITLE
Patch 107 (Issue 107 resolve)

### PR DESCRIPTION
**Pull request by greysondn**
This seemed like the best way to do this. ~~I apologize that my name is inconsistent throughout these commits, but~~ the work is done now to present date.

Edit: This is the work that @moly wanted to see merged in from #107 .

Edit 2: I added the missing data to my account to remedy this name-changes-a-lot thing for all past and future ndeavors

### CODE REVIEW

**Comment by greysondn** [comment]
My repo fork has been scrpped. I'll redo the work "soon" if it's not already done. I still feel this was a good piece of work but we already determined that this was a bad fork due to the need to keep patches in from a separate dev team's needs. Long story short, I no longer have any obligations to them :)

I'm closing this. The code does not exist to pull in any longer.

**Comment by Dovyski** [comment]
We will wait for your new pull request :) This is a very important improvement that must be merged into Flixel.

**Comment by greysondn** [comment]
Was this ever done? I'm about to have an explosive quadtree problem and would be okay with volunteering to do it a second time right about... on the year anniversary of the last comment.

**Comment by greysondn** [comment]
I see you're round and about. I'm working on this right now. When I touched the code, it hadn't been done yet.

I should have a pull request for you within the next six hours unless something goes disastrously wrong.

**Comment by Dovyski** [comment]
Yeah, things have been crazy in the past few months, but I am trying to slowly get back :)

Regarding your PR, nice, thanks! I have a quad-tree demanding game I can use to check if everything is ok. I let you know if I find any problems.

**Comment by greysondn** [comment]
Are we dead yet?

**Comment by Dovyski** [comment]
Maybe :D

I think things have slowed down to a halt around here, so I don't know the exact point where are at the moment.

**Comment by greysondn** [comment]
Hm.

I hate the "AS3 is dying! SO LONG FLASH!" people. I don't see it as capable of dying; HTML5 doesn't provide a sane way to protect source code while providing all of the binary to the end user, which means that JS isn't the future, either. But that's a big question I've had and the death of flixel's AS3 aspects seem to match the pace of abandoning Flash as a whole.

An observation, and partial explanation of why I never stopped, too.

**Comment by Dovyski** [comment]
I hate that king of discussion too, but it is pretty hard to see a company-backed platform being ignored by that very same company. I think AS3 is superior in so many way to JS as well, but I don't like the idea of investing my time on something Adobe might terminate in the near future.

I've think [HaxeFlixel](http://haxeflixel.com/) is the way to go :)

**Pull request closed without merging**
