### PR TITLE
Make repository documentation into Markdown

### PR DESCRIPTION
**Pull request by IQAndreas**
The `LICENSE` and `README` have been changed from `txt` files to Markdown files, and have been "prettified" a bit.

Also added a `CONTRIBUTING` file; see the following blog post for more information: https://github.com/blog/1184-contributing-guidelines

### CODE REVIEW

**Comment by IQAndreas** [comment]
If anyone wants a preview of how the result looks (and this look is automatically parsed by GitHub as you can see):
- [README](https://github.com/IQAndreas/flixel/blob/readme-markdown/README.md)
- [LICENSE](https://github.com/IQAndreas/flixel/blob/readme-markdown/LICENSE.md)
- [CONTRIBUTING](https://github.com/IQAndreas/flixel/blob/readme-markdown/CONTRIBUTING.md)

**Comment by IQAndreas** [comment]
There are a few last changes I want to make before the merge.

**README**
I would like to add information about what the FlixelCommunity version is, that it's not maintained by Adam Atomic, but still has his blessing.

Perhaps we can add any part of this quote as well:

> If you want to build your own Flixel-based library I strongly encourage you to just go ahead and do that! Even though I have been quite busy for the last year, I am not yet comfortable allowing user contributions on the official Flixel branch. I do have plans for Flixel, they've just been waylaid for babies and houses and things recently...
> 
> You are more than welcome to create a new github project based on Flixel though, and grow it and maintain it to your heart's content (and even offer it as an alternative to the flixel userbase!)

**LICENSE**
Since the FlixelCommunity version of Flixel is technically a derivative work with additional changes by a different copyright holder, should we change the beginning of the file and add that additional information:

```
Copyright (c) 2009 Adam 'Atomic' Saltsman
Copyright (c) 2013 FlixelCommunity Team 
```

Or is that too _____? (I can't find an adjective, "strong" maybe?)

**CONTRIBUTING**

Is the information clear enough? Should I add or remove anything? I'm worried about having too much information, causing people who want to pull request to _"TL;DR"_.

Does the recommended `dev` alias fit in there, or should I remove it?

**Comment by Dovyski** [comment]
Amazing! I've been planning to write that pull request for a long time, I am glad you did it :)

**README**

> I would like to add information about what the FlixelCommunity version is, that it's not maintained by Adam Atomic, but still has his blessing. Perhaps we can add any part of this quote as well

That's a great idea! I think we should add some clear information about FlixelCommunity, specially that it was not created to replace Flixel, but to live side by side with a healthy directional/management difference.

I liked the quote, but isn't it too harsh? Perhaps something like:

> You are more than welcome to create a new github project based on Flixel though, and grow it and maintain it to your heart's content (and even offer it as an alternative to the flixel userbase!) .

I also think we should change the following in the README file:
- Drop the **History** stuff;
- Add a few more sections to give a glimpse of the whole project, pretty much like [this one](https://github.com/twitter/bootstrap) (from Twitter's Bootstrap).

**LICENSE**
I think we can't change the copyright notice. Shall we add another license block with the "Flixel Community Team" copyright note?

We should take a look at other open source projects and check how they do that.

**CONTRIBUTING**
This file is really good, but I think the information is too "dense". Maybe we could simplify it a little bit making the text easier and quicker to read.

**Comment by IQAndreas** [comment]
All good proposals, but I'm unsure how to word them specifically.

Do you think you could branch off of my branch (named [readme-markdown](https://github.com/IQAndreas/flixel/tree/readme-markdown)), make the changes you feel are fitting, and I will merge those changes into this pull request?

> Shall we add another license block with the "Flixel Community Team" copyright note?

I assumed we were required to use the same copyright license anyway, especially since our changes are so intertwined with Adam's code that it's difficult to separate them. So it would just be repeated information. But as much as I have _tried_ to research it, I'm still quite shaky on copyright law when it comes to code.

**Comment by Dovyski** [comment]
Sure, I will branch off your work and add my suggestions.

About the copyright, I think we cannot change the "Adam" line because it's tampering with the original author. That's why I suggested adding another block (using the same license). I will check other open source projects to learn how they do.

**Comment by IQAndreas** [comment]
> About the copyright, I think we cannot change the "Adam" line because it's tampering with the original author.

Sorry, I should have clarified, I don't want to change the original line. I want to add another one as additional information, like this: https://github.com/IQAndreas/flixel/blob/readme-markdown/LICENSE.md

**Comment by IQAndreas** [comment]
I don't mean to rush you, but I would like to give you a friendly poke. I figure once we have a `CONTRIBUTING` file we can start inviting other developers to help hammer out the last of the issues.

Also, nice work on [the site](http://flixelcommunity.github.com/), it looks amazing. :)

**Comment by Dovyski** [comment]
Thanks for the friendly poke! I've been hell busy those last days because of the end of the semester. Things are slowing down this week, so I should get back to work on this issue. I think you could merge the pull now and let me add any suggestions in the future, what do you think? 

About the site, thank you! :)

**Comment by IQAndreas** [comment]
> I think you could merge the pull now and let me add any suggestions in the future, what do you think?

Sounds good to me. I added the "A community version. Not a replacement." bit from the site to the README just so there is something in the meantime: https://github.com/IQAndreas/flixel/blob/readme-markdown/README.md

One last question, is the change to the license alright, or should I undo it before merging?
https://github.com/IQAndreas/flixel/blob/readme-markdown/LICENSE.md

**Comment by Dovyski** [comment]
> One last question, is the change to the license alright, or should I undo it before merging?

I think you should undo and make it differently. I've found a [great article](http://www.lshift.net/blog/2012/04/11/open-source-attribution-and-contribution) about open source license and contribution. The author suggests the following (which I think is perfect and fair):

`Copyright (c) 2009 Adam 'Atomic' Saltsman and other contributors (see the CONTRIBUTORS file).`

The author describes the CONTRIBUTORS file:

> and the CONTRIBUTORS file can have some broad, plain-english description of who added what, or just simply be a list of people. Since you’re just referencing a file, CONTRIBUTORS can list those who have contributed code and those who have contributed other ideas.
> 
> While it’s by no means a novel idea, it does allow you to make it very clear that you’ve received contributions which are okay to modify and reuse, and, secondly, makes it very clear who those people are! Attribution is thus covered. As an extra bonus, if a contributor adds their own name to the CONTRIBUTORS file, then — in combination with some clear, up-front contribution guidelines — that’s a good, simple indicator that they’re sending you work under the same terms.

It would be great if we could create some sort of contribution guide, where any developer can send pull requests, but among the changes he must include his name in the CONTRIBUTORS (if it's not there already).

**Comment by IQAndreas** [comment]
> I think you should undo and make it differently. I've found a great article about open source license and contribution. The author suggests the following (which I think is perfect and fair):
> `Copyright (c) 2009 Adam 'Atomic' Saltsman and other contributors (see the CONTRIBUTORS file).`

I was starting to add a `CONTRIBUTORS` file, when I realized GitHub already has such a feature:
https://github.com/blog/643-contributors

The layout has changed, but it can still be reached with the same URL:
http://github.com/FlixelCommunity/flixel/contributors

Instead of adding a new text file, what if we reference the GitHub url? That would ensure that the list of contributors is always up to date.

```
Copyright (c) 2009 Adam 'Atomic' Saltsman and other contributors.  
Full list at http://github.com/FlixelCommunity/flixel/contributors
```

_(I wasn't sure if the URL could be a markdown link, or if the URL needs to be written out in plaintext for legal reasons)_

**Comment by Dovyski** [comment]
I think that URL fits perfectly. If someone didn't like the URL (or it is legally wrong), we can create the `CONTRIBUTORS` file in the future.

**Comment by IQAndreas** [comment]
I added the final changes, so the files now look like this:
- [README](https://github.com/IQAndreas/flixel/blob/readme-markdown/README.md)
- [LICENSE](https://github.com/IQAndreas/flixel/blob/readme-markdown/LICENSE.md)
- [CONTRIBUTING](https://github.com/IQAndreas/flixel/blob/readme-markdown/CONTRIBUTING.md)

If you are satisfied with the result, you can merge and close the pull request.

**Pull request merged**
