### PR TITLE
Fix bug in #overlaps and #overlapsAt that would lead to only the first e...

### PR DESCRIPTION
**Pull request by moly**
...lement of a FlxGroup being checked by using the wrong length variable.

Fixed FlixelCommunity/flixel#9, AdamAtomic/flixel#223
Fixed FlixelCommunity/flixel#54, AdamAtomic/flixel#177

### CODE REVIEW

**Comment by Dovyski** [comment]
I've tested and it does not work. As soon as you fix the `length` problem, both methods start to analyze all members of the group. If any of them is `null`, the both methods crash.

Since this is an "external" pull request, I thought it would be faster just to fix it myself :). My pull request containing **rogerbraun**'s and my own fixes is https://github.com/FlixelCommunity/flixel/pull/109

**Comment by Dovyski** [comment]
@moly I've noticed you already have an open pull request (https://github.com/FlixelCommunity/flixel/pull/98) containing a fix for several issues involving `overlap*()`, including `FlxTileMap.overlap()`.

For that reason, I think this pull request here will only produce merge conflicts. It should be closed without merge, what do you guys think?

**Comment by moly** [comment]
I didn't organise the commits very well for this issue. Feel free to merge/close as you see fit.

**Comment by Dovyski** [comment]
Ok, I will merge some of my changes with your commits.

**Pull request closed without merging**
