### PR TITLE
Advanced FlxSprite

### PR DESCRIPTION
**Pull request by mezkhalin**
Adds a subclass of FlxSprite that enables it to support both baked rotation and animations.

### CODE REVIEW

**Comment by Dovyski** [comment]
Nice addition! I'm curious why you decided to create another class instead of merging that feature with `FlxSprite` itself. Anything in particular?

**Comment by mezkhalin** [comment]
Well it started out for clarity's sake, but now that you mention it. I'll go ahead and merge it with FlxSprite in the upcoming days.

**Comment by Gama11** [comment]
@Dovyski Are you sure it's a good idea to merge this into the core `FlxSprite`? There are millions of features that could be added to that, and evenutally it would just be a cluttered mess. 
Not saying this particular feature is useless.. just maybe not that essential, so it has to be considered very well if this should go straight into `FlxSprite`.

**Comment by mezkhalin** [comment]
@Gama11 In my point of view this class merges two core functions of `FlxSprite`; animation and rotation which is why I endorse merging them.
I agree that nonessential functions could be collected into an extended class as not to clutter the core class, but I don't consider animation and rotation to be nonessential.

**Pull request closed without merging**
