### PR TITLE
Update `flx.py` and move it to `utils` folder

### PR DESCRIPTION
**Pull request by IQAndreas**
This pull requests merges in the changes made by @ivangonekrazy, as well as moves the python script to the `utils` folder.

### CODE REVIEW

**Comment by IQAndreas** [comment]
I haven't actually verified the changes made by @ivangonekrazy, I simply made it into a pull request.

Thomas, you were the one who was familiar with Python, correct? Could you take a look at the script and make sure it looks good, and second, if it has been affected by moving the script (will it look for the source in the `utils` folder, or will it look in the same folder as the script is called from?)

Also, should we rename the script to be more descriptive? For example `generate-flixel-project.py`? (are there any better names?)

**Comment by Dovyski** [comment]
I think `generate-flixel-project.py` is way better than `flx.py`.

**Comment by moly** [comment]
I think part of the reason for the short name is so that it's easy to run from the command line.

**Comment by IQAndreas** [comment]
> I think part of the reason for the short name is so that it's easy to run from the command line.

Ah, yes, that must have been the case. However, since you don't need any arguments (the variables are all defined in the script) the script can be run by double clicking it (at least in Linux), no typing necessary.

Or, if you really want to use the command line, you only need to write two or three characters of the script name and you can tab to auto-complete the script name.

For that reason, I think I'll use the name suggested by @Dovyski, and include the change in this pull request.

**Comment by moly** [comment]
> However, since you don't need any arguments (the variables are all defined in the script

We could easily edit it so that it takes arguments, would make it much more useful. For some reason the current script takes the project name as an argument but nothing else.

**Pull request merged**
