### PR TITLE
Organize Flixel into packages

### PR DESCRIPTION
**Pull request by IQAndreas**
Fixes https://github.com/FlixelCommunity/flixel/issues/194

Changes:
- Organize Flixel, moving many of the classes elsewhere or into new packages as per [the spreadsheet created by Ka Wing](https://docs.google.com/spreadsheet/ccc?key=0Avkk09kHolxjdGlqV3BTNkRVWWU0VDFfa0JhcFJMRVE&usp=sharing)
- Rename `FlxAnim` to `FlxAnimation`

The following are proposed changes, which we still need to confirm before I add them to the pull request:
- Rename `FlxRect` to `FlxRectangle` - _**PRO:** Full name instead of abbreviation, just like the other classes in the same package. **CON:** Will not match HaxeFlixel._
- Rename `FlxList` to `FlxLinkedList` - _**PRO:** More descriptive; `List` is a very ambiguous name. **CON:** Will not match HaxeFlixel._

### CODE REVIEW

**Comment by Dovyski** [comment]
About the renames, I think we should keep `FlxRect` and `FlxList`.

**Comment by Dovyski** [comment]
Feel free to merge this anytime, so we can start working on the remaining tasks without merge conflicts :)

**Comment by Gama11** [comment]
I went ahead and made the `FlxList` -> `FlxLinkedList` change in HaxeFlixel. It's a way better name in my opinion. :)

**Comment by Dovyski** [comment]
Awesome! :D

**Pull request merged**
