### PR TITLE
#111 more FDT/FlashBuilder warnings removed

### PR DESCRIPTION
**Pull request by WingEraser**
`Input` class got two new classes: `KeyData` and `KeyState`. They will eliminate the silly look ups (and those warnings). This will affect `Keyboard` and `FrameRecord` class.

`FlxSprite` got a safe cast of `_animation[i].name as FlxAnim`. `_animation` array only holds `FlxAnim`.

I can solve the most others as well by safe casting. Not sure if it is worth.

### CODE REVIEW

**Comment by IQAndreas** [comment]
Actually, I figured pretty much all of those "dynamic variable" warnings would be fixed when we [switch to using Vectors instead of Arrays](https://github.com/FlixelCommunity/flixel/issues/104).

But the `KeyData` and `KeyState` classes should really come in handy, since they should also help with performance. Mind if we push those two additions to the next version? (which should be next week if everything goes as planned)

_Also, I knew forcing a re-write of the commit history was going to backfire._ :P _When working on the code today, I noticed a bug in an earlier commit, so rather than create a new commit fixing it, I went back, edited it, and re-did the earlier commits. I figured "no one will notice if the commit history is different than it was an hour ago; and it's a weekend, so no one but me will be working anyway."_ ;)

_That's why you have two extra commits by me in your pull request; my mistake._

**Comment by WingEraser** [comment]
You can thank moly for those two classes, they were implemented first at flixel-gdx as an inner class of `Input`. Most "dynamic variable" can indeed be solved by using Vectors. I don't know about the performance these days (FP 11.9). It can't be hurt, as I see the most classes that can be replaced with Vector aren't used during the loop.

There are some classes with `Object` that doesn't know 'toString()'. I found `ObjectUtil` which extends `Object`. Is just a small class with 'toString()'  available. However I can't find it in Flex SDK 4.6 which should be according the documentation. Another thing, I tried to run flixel with Apache Flex SDK 4.10, but it didn't work. It could be either FDT4 fault. Google search only found fault with FDT 4 and 5. I haven't tried FlashDevelop yet.

**Comment by IQAndreas** [comment]
> There are some classes with Object that doesn't know 'toString()'.

Actually, it's defined in the `prototype` chain, so `toString()` is always available, although the output isn't always pretty; you can instead add your own `toString()` method if the need arises. I'm not sure where something like that would be noted in the documentation.

> I tried to run flixel with Apache Flex SDK 4.10, but it didn't work.

Did you get any error messages? If you are on OSX or Linux, try using the script `utils/generate-swc.sh` and let me know what it says.

**Comment by WingEraser** [comment]
> Did you get any error messages? If you are on OSX or Linux, try using the script utils/generate-swc.sh and let me know what it says.

It seems an error with FDT4 and 5. I simply can't compile. This is the error:

```
An internal error occurred during: "Compile".
java.lang.NullPointerException
```

I'm using Windows 7 x64. I couldn't get FDT running on Linux x64. It can't find the debugger. I'm not a Linux guru. Oh well, this is off topic.

**Comment by IQAndreas** [comment]
> It seems an error with FDT4 and 5. I simply can't compile.

Do you get any more detailed output when you run FDT in the terminal? If all else fails, you can submit a bug report for it: http://bugs.powerflasher.com/jira/browse/FDT

> I couldn't get FDT running on Linux x64. It can't find the debugger.

That's actually [an FDT bug that they are working on fixing](http://bugs.powerflasher.com/jira/browse/FDT-2436). What I do (as I described in the bug report) is download the standalone Flash player and debug with that, then it works.

**Comment by WingEraser** [comment]
> Do you get any more detailed output when you run FDT in the terminal? If all else fails, you can submit a bug report for it: http://bugs.powerflasher.com/jira/browse/FDT

Nopes, no other details than this: Starting Launcher Main. No windowed Flash Player and neither can I stop by clicking the red stop button.

> That's actually an FDT bug that they are working on fixing. What I do (as I described in the bug report) is download the standalone Flash player and debug with that, then it works.

A bug report from 2011 and still not fixed. I seems they moved and let the bugs hanging on old FDT versions. I only got license for FDT4. Will try the solution once I'm back at my Linux system.

**Pull request closed without merging**
