### PR TITLE
Merge AdamAtomic/dev into FlixelCommunity/dev

### PR DESCRIPTION
**Pull request by moly**
The AdamAtomic /dev branch contains a couple of useful additions. Would be good to include them in our branch also.

### CODE REVIEW

**Comment by IQAndreas** [comment]
Something odd about those changes, he already has "added readme file finally" and "minor readme edits" in his `master` branch, but using different commits. Perhaps he had some commits after those changes.

I think the easiest thing to do is pull the other four commits out and merge them in. It's a small amount of work, but I can take care of it.

**Comment by IQAndreas** [comment]
Also, the last one, "[added a function to trigger basic full-screen support](https://github.com/AdamAtomic/flixel/commit/2c1e5dc790e74b1ebeeb2ccd28a677a640c00f10)", needs some more work, as @noio mentions in the following commit:
https://github.com/IQAndreas/flixel/commit/5b625dccbd352ce5540eb7f6251cd0df501fb417

The recommended changes by Noio also need some improving (as he says, listening for a resize) before I feel comfortable pulling it in.

**Comment by moly** [comment]
There shouldn't really be any problem merging in duplicate commits, they just won't do anything.

**Comment by IQAndreas** [comment]
> There shouldn't really be any problem merging in duplicate commits, they just won't do anything.

Though for some reason, they are registered with different commit IDs. Is GIT smart enough to recognize that the changes are identical anyway, or will we get merge conflicts?

**Comment by Dovyski** [comment]
I don't know if git is smart enough to get that, but in case we get merge conflicts, it should be easy to solve, because they should be identical commits. Just pick all changes from one and ignore all changes from the another.

About the full-screen support, I agree we need some more work on it. Listening for a resize event is the ideal solution instead of checking the screen size every frame.

**Pull request merged**
