### PR TITLE
Fix FlxTilemap can't draw one-column tilemap

### LINKED ISSUE #212: FlxTilemap() can't draw one-column tilemap - BitmaData exception
When I try to call `loadMap(FlxTilemap.arrayToCSV(constructBoundsArray("LEFT"), 1) ...` flash throws

```
ArgumentError: Error #2015: Invalid BitmapData.
    at flash.display::BitmapData/ctor()
    at flash.display::BitmapData()
    at org.flixel.system::FlxTilemapBuffer()[E:\workspace-flash\frameworks\AdamAtomic-flixel-8989e50\org\flixel\system\FlxTilemapBuffer.as:72]
    at org.flixel::FlxTilemap/draw()[E:\workspace-flash\frameworks\AdamAtomic-flixel-8989e50\org\flixel\FlxTilemap.as:426]
```

It making impossible to draw a "one-column" tilemap (border for something, as example)
Fix is:  in `FlxTilemap.loadMap()` function find rows

```
                columns = rows[row++].split(",");
                if(columns.length <= 1)
```

replace `<=` with `<`
That should work.

### PR DESCRIPTION
**Pull request by Dovyski**
Fix #212

### CODE REVIEW

**Comment by IQAndreas** [comment]
What happened here? (lots of commits merged) It looks like it was mistakenly merged into `master` instead of `dev`.

**Comment by IQAndreas** [comment]
> ... the commit log shows more commits than I added myself. [...] that's because I created a pull request against master. I will change that before merging.

Ah, yes, I see it happened elsewhere as well.

Also noticed you added a "revert commit". It's probably easier (and would make the git history MUCH clearer for people looking at the history years from now) if this was reset to a previous commit, instead of creating a whole bunch of "junk" in the history.

Let me know if you would like me to manually do the revert; I have done so before.

**Comment by Dovyski** [comment]
> What happened here? (lots of commits merged) It looks like it was mistakenly merged into master instead of dev.

That's what happens when git kids do merging stuff unsupervised by adults :D 

> Also noticed you added a "revert commit". It's probably easier (and would make the git history MUCH clearer for people looking at the history years from now) if this was reset to a previous commit, instead of creating a whole bunch of "junk" in the history.
> 
> Let me know if you would like me to manually do the revert; I have done so before.

Totally agree! It would be great if you could manually do the revert and clean up this mess. Thank you very much!

**Comment by IQAndreas** [comment]
> Totally agree! It would be great if you could manually do the revert and clean up this mess. Thank you very much!

Done! You may still need to "fix" your local version of the branch by doing something like (haven't tested any of the code, but it _should_ work as expected...

```
# Assuming your "remote" is named FlixelCommunity
git fetch FlixelCommunity

# Remove your "invalid" copy of "master"
# It's easier just deleting it and re-adding it instead of fiddling with forcing a pull
git branch -D master
git checkout -b FlixelCommunity/master
git push origin --set-upstream master -f

# Update to the lastest version of "dev" (now with your new pull request)
git checkout dev
git pull FlixelCommunity/dev
git push origin

# These steps may or may not be necessary, depending on how your local setup looks
# Remove the old 'revert-216-fix-issue-212' branch (if it shows up in the list if you run `git branch -a`)
git branch -d revert-216-fix-issue-212 # Remove it locally
git push orgin :revert-216-fix-issue-212 # Remove it remotely
```

This problem keeps happening (and has happened to me, but I noticed it before publishing the pull request) because we changed the "main" branch from `dev` to `master`.

Although we may be tempted to change the main branch back to `dev` to make pull requests easier, I think it's still a better idea to keep `master` as main, so anyone that visits the project and downloads the source gets the "stable" version. We are just going to have to keep an eye on ourselves to make sure we merge to the correct branch (you select it when you open the pull request).

**Comment by Dovyski** [comment]
Thank you very much! Everything seems as it should be now :)

About the main branch, I agree we should keep `master` there. I will pay more attention next time I create a pull request.

**Pull request merged**
