### PR TITLE
Missing usage of particleClass in FlxEmitter

### PR DESCRIPTION
**Pull request by moly**
FlxEmitter now uses the custom particle class to recycle instead of FlxParticle.
Fixed FlixelCommunity/flixel#6, AdamAtomic/flixel#226

### CODE REVIEW

**Comment by IQAndreas** [comment]
Looks good to me.

On a different note, you still run the risk of the user assigning an object that isn't a `FlxParticle` (there doesn't seem to be error handling for that, should there be?), but hopefully developers are smart enough to keep that in mind.

**Comment by Dovyski** [comment]
Looks ok to me too.  If think it would be useful to log a warning if a class that isn't a `FlxParticle` is used. At least it will give the developer a clue when an exception pops up an ugly stack trace during the particles instantiation.

**Comment by IQAndreas** [comment]
Is there a clever way to see if a `Class` object is of a certain type?
- Create one instance and check it?
- Parse it out of `describeType()`?

**Comment by moly** [comment]
Easiest way is probably just to put a try catch around `particle = new particleClass();` and `particle = recycle`

**Comment by IQAndreas** [comment]
@moly Since you already have this pull request open, do you want to add that feature, or is it better to keep it separated as a different merge?

**Comment by moly** [comment]
I'll just add it here.

**Comment by Dovyski** [comment]
It will produce several log entries. Shouldn't we create a setter for `particleClass` and there verify if the class is good? It will produce just a single log entry in case of problem.

Additionally I think the log message should display the problematic `particleClass`, someting like `"error.." + particleClass + " more text"`. It will help the developer to find the malfunctioning emitter.

**Comment by IQAndreas** [comment]
If I may (to compensate for me feeling so helpless in many of the other open pull requests):

``` as3
protected var _particleClass:Class;
public function get particleClass():Class
{
    return _particleClass;
}
public function set particleClass(value:Class):void
{
    var testParticle:* = new value();
    if (testParticle is FlxParticle)
    {
        _particleClass = value;
    }
    else
    {
        FlxG.log("ERROR: " + getQualifiedClassName(testParticle) " must extend FlxParticle in order to be used in a FlxEmitter.");
    }
}
```

Adam doesn't use enough getters and setters, and I find that to be a shame.

**Comment by Dovyski** [comment]
Exactly what I had in mind, @IQAndreas.

**Comment by IQAndreas** [comment]
@moly - Do you want to merge in my `fix-flxemitter-particleclass` branch into this pull request?
https://github.com/IQAndreas/flixel/tree/fix-flxemitter-particleclass

It includes the fixes we mentioned here.

**Comment by IQAndreas** [comment]
@moly Hey, what did you do with my fancy `getQualifiedClassName()`? ;)

**Comment by IQAndreas** [comment]
It might be a good idea also changing the ASDoc a tad more so as to resolve the issue https://github.com/FlixelCommunity/flixel/issues/47

```
/**
* Set your own particle class type here. The custom class must extend <code>FlxParticle</code>.
* Default is <code>FlxParticle</code>.
*/
```

That way users don't need to trigger the error before learning about this restriction.

**Comment by Dovyski** [comment]
I agree (it should already be there :)

**Comment by IQAndreas** [comment]
I just noticed Flixel has it's own function for retrieving the class name:

```
FlxU.getClassName(testParticle);
```

Could you add a commit with this change, and include the addition to the ASDoc?

**Comment by Dovyski** [comment]
I think it is useful. The complete class name will make things easier for developers to spot bugs.

**Comment by IQAndreas** [comment]
@moly Great! I didn't realize you had already added the commits.

I didn't realize this before, but GitHub does not seem to notify when updates are added, only when comments are made. We should probably post a quick comment whenever we add or edit commits.

These changes look good to me, so I'll go ahead and merge them in.

**Pull request merged**
