### PR TITLE
Remove ASDoc and `build_docs.sh`

### PR DESCRIPTION
**Pull request by IQAndreas**
Perhaps we can move the documentation to a submodule, or [GitHub Pages](http://pages.github.com/).

Regardless, it does not belong in the main repository, especially when we are constantly updating the code, and can't re-build the documentation with every commit. Documentation updating only needs to be done with each new release.

### CODE REVIEW

**Comment by moly** [comment]
Creating a github pages when we're done sounds like a good idea.

**Comment by IQAndreas** [comment]
Should we delete `build_docs.sh` as well (at least for now) or move it to a separate folder?

**Comment by Dovyski** [comment]
The github page seems good to me too. About the `build_docs.sh`, I think we should move it to a separate folder (like `utils`).

**Comment by IQAndreas** [comment]
I edited the commit to remove the ASDoc (as before) but this time moved the script to a new `utils` folder.

The `build_docs.sh` also needed some updating to be more "other users friendly", so I figured I would do so while I was at it.

**Comment by Dovyski** [comment]
Looks ok to me.

**Pull request merged**
